apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: mysql
stringData:
  database-name: MYSQL_DATABASE
  database-password: MYSQL_PASSWORD
  database-root-password: MYSQL_ROOT_PASSWORD
  database-user: MYSQL_USER
