apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: mysql
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageclass }}
  resources:
    requests:
      storage: 10Gi
